//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.SceneManagement;

public static partial class ResourcePaths
{
        public static partial class Scenes
        {

            public const string GameScene = "TradeCity.Unity/Scenes/GameScene";
            public static void LoadGameScene(LoadSceneMode mode = LoadSceneMode.Single) => SceneManager.LoadScene(GameScene, mode);
            public static AsyncOperation LoadAsyncGameScene(LoadSceneMode mode = LoadSceneMode.Single) => SceneManager.LoadSceneAsync(GameScene, mode);

            public const string MainMenu = "TradeCity.Unity/Scenes/MainMenu";
            public static void LoadMainMenu(LoadSceneMode mode = LoadSceneMode.Single) => SceneManager.LoadScene(MainMenu, mode);
            public static AsyncOperation LoadAsyncMainMenu(LoadSceneMode mode = LoadSceneMode.Single) => SceneManager.LoadSceneAsync(MainMenu, mode);

        }

        public static partial class Sprites
        {

            public const string CityBackground = "Screen/CityBackground";
            public static Sprite LoadCityBackground() => Resources.Load<Sprite>(CityBackground);

            public const string CityInternal = "Screen/CityInternal";
            public static Sprite LoadCityInternal() => Resources.Load<Sprite>(CityInternal);

            public const string CityNight = "Screen/CityNight";
            public static Sprite LoadCityNight() => Resources.Load<Sprite>(CityNight);

            public const string Europe_Map_Poster = "Screen/Europe-Map-Poster";
            public static Sprite LoadEurope_Map_Poster() => Resources.Load<Sprite>(Europe_Map_Poster);

            public const string MapPlaceholder = "Screen/MapPlaceholder";
            public static Sprite LoadMapPlaceholder() => Resources.Load<Sprite>(MapPlaceholder);

            public const string marketPlaceholder = "Screen/marketPlaceholder";
            public static Sprite LoadmarketPlaceholder() => Resources.Load<Sprite>(marketPlaceholder);

            public const string stockmarket = "Screen/stockmarket";
            public static Sprite Loadstockmarket() => Resources.Load<Sprite>(stockmarket);

            public const string preview = "Gameicons/preview";
            public static Sprite Loadpreview() => Resources.Load<Sprite>(preview);

            public const string brick_pile = "Resource/brick-pile";
            public static Sprite Loadbrick_pile() => Resources.Load<Sprite>(brick_pile);

            public const string broken_bottle = "Resource/broken-bottle";
            public static Sprite Loadbroken_bottle() => Resources.Load<Sprite>(broken_bottle);

            public const string bunker = "Resource/bunker";
            public static Sprite Loadbunker() => Resources.Load<Sprite>(bunker);

            public const string chemical_drop = "Resource/chemical-drop";
            public static Sprite Loadchemical_drop() => Resources.Load<Sprite>(chemical_drop);

            public const string coal_pile = "Resource/coal-pile";
            public static Sprite Loadcoal_pile() => Resources.Load<Sprite>(coal_pile);

            public const string commercial_airplane = "Resource/commercial-airplane";
            public static Sprite Loadcommercial_airplane() => Resources.Load<Sprite>(commercial_airplane);

            public const string concrete_bag = "Resource/concrete-bag";
            public static Sprite Loadconcrete_bag() => Resources.Load<Sprite>(concrete_bag);

            public const string cubes = "Resource/cubes";
            public static Sprite Loadcubes() => Resources.Load<Sprite>(cubes);

            public const string electric = "Resource/electric";
            public static Sprite Loadelectric() => Resources.Load<Sprite>(electric);

            public const string gas_pump = "Resource/gas-pump";
            public static Sprite Loadgas_pump() => Resources.Load<Sprite>(gas_pump);

            public const string i_beam = "Resource/i-beam";
            public static Sprite Loadi_beam() => Resources.Load<Sprite>(i_beam);

            public const string log = "Resource/log";
            public static Sprite Loadlog() => Resources.Load<Sprite>(log);

            public const string money_stack = "Resource/money-stack";
            public static Sprite Loadmoney_stack() => Resources.Load<Sprite>(money_stack);

            public const string oil_drum = "Resource/oil-drum";
            public static Sprite Loadoil_drum() => Resources.Load<Sprite>(oil_drum);

            public const string ore = "Resource/ore";
            public static Sprite Loadore() => Resources.Load<Sprite>(ore);

            public const string paint_bucket = "Resource/paint-bucket";
            public static Sprite Loadpaint_bucket() => Resources.Load<Sprite>(paint_bucket);

            public const string person = "Resource/person";
            public static Sprite Loadperson() => Resources.Load<Sprite>(person);

            public const string powder = "Resource/powder";
            public static Sprite Loadpowder() => Resources.Load<Sprite>(powder);

            public const string quill_ink = "Resource/quill-ink";
            public static Sprite Loadquill_ink() => Resources.Load<Sprite>(quill_ink);

            public const string refinery = "Resource/refinery";
            public static Sprite Loadrefinery() => Resources.Load<Sprite>(refinery);

            public const string rolled_cloth = "Resource/rolled-cloth";
            public static Sprite Loadrolled_cloth() => Resources.Load<Sprite>(rolled_cloth);

            public const string stone_block = "Resource/stone-block";
            public static Sprite Loadstone_block() => Resources.Load<Sprite>(stone_block);

            public const string unknown = "Resource/unknown";
            public static Sprite Loadunknown() => Resources.Load<Sprite>(unknown);

            public const string water_drop = "Resource/water-drop";
            public static Sprite Loadwater_drop() => Resources.Load<Sprite>(water_drop);

            public const string wood_beam = "Resource/wood-beam";
            public static Sprite Loadwood_beam() => Resources.Load<Sprite>(wood_beam);

            public const string sheet_black1x = "Gameicons/Spritesheet/sheet_black1x";
            public static Sprite Loadsheet_black1x() => Resources.Load<Sprite>(sheet_black1x);

            public const string sheet_black2x = "Gameicons/Spritesheet/sheet_black2x";
            public static Sprite Loadsheet_black2x() => Resources.Load<Sprite>(sheet_black2x);

            public const string sheet_white1x = "Gameicons/Spritesheet/sheet_white1x";
            public static Sprite Loadsheet_white1x() => Resources.Load<Sprite>(sheet_white1x);

            public const string sheet_white2x = "Gameicons/Spritesheet/sheet_white2x";
            public static Sprite Loadsheet_white2x() => Resources.Load<Sprite>(sheet_white2x);

            public const string crane = "Resource/CategoryIcons/crane";
            public static Sprite Loadcrane() => Resources.Load<Sprite>(crane);

            public const string factory = "Resource/CategoryIcons/factory";
            public static Sprite Loadfactory() => Resources.Load<Sprite>(factory);

            public const string modern_city = "Resource/CategoryIcons/modern-city";
            public static Sprite Loadmodern_city() => Resources.Load<Sprite>(modern_city);

            public const string oil_pump = "Resource/CategoryIcons/oil-pump";
            public static Sprite Loadoil_pump() => Resources.Load<Sprite>(oil_pump);

            public const string pylon = "Resource/CategoryIcons/pylon";
            public static Sprite Loadpylon() => Resources.Load<Sprite>(pylon);

            public const string coal_powerplant = "Structure/Building/coal_powerplant";
            public static Sprite Loadcoal_powerplant() => Resources.Load<Sprite>(coal_powerplant);

            public const string Default = "Structure/Building/Default";
            public static Sprite LoadDefault() => Resources.Load<Sprite>(Default);

            public const string steel_forge = "Structure/Building/steel_forge";
            public static Sprite Loadsteel_forge() => Resources.Load<Sprite>(steel_forge);

            public const string Clearwaterlake = "Structure/Land/Clearwaterlake";
            public static Sprite LoadClearwaterlake() => Resources.Load<Sprite>(Clearwaterlake);

            public const string CoalMine = "Structure/Land/CoalMine";
            public static Sprite LoadCoalMine() => Resources.Load<Sprite>(CoalMine);

            public const string Forest = "Structure/Land/Forest";
            public static Sprite LoadForest() => Resources.Load<Sprite>(Forest);

            public const string IronMine = "Structure/Land/IronMine";
            public static Sprite LoadIronMine() => Resources.Load<Sprite>(IronMine);

            public const string OilField = "Structure/Land/OilField";
            public static Sprite LoadOilField() => Resources.Load<Sprite>(OilField);

            public const string OilRig = "Structure/Land/OilRig";
            public static Sprite LoadOilRig() => Resources.Load<Sprite>(OilRig);

            public const string SandQuarry = "Structure/Land/SandQuarry";
            public static Sprite LoadSandQuarry() => Resources.Load<Sprite>(SandQuarry);

            public const string StoneQuarry = "Structure/Land/StoneQuarry";
            public static Sprite LoadStoneQuarry() => Resources.Load<Sprite>(StoneQuarry);

            public const string Well = "Structure/Land/Well";
            public static Sprite LoadWell() => Resources.Load<Sprite>(Well);

            public const string arrowDown = "Gameicons/PNG/White/2x/arrowDown";
            public static Sprite LoadarrowDown() => Resources.Load<Sprite>(arrowDown);

            public const string arrowLeft = "Gameicons/PNG/White/2x/arrowLeft";
            public static Sprite LoadarrowLeft() => Resources.Load<Sprite>(arrowLeft);

            public const string arrowRight = "Gameicons/PNG/White/2x/arrowRight";
            public static Sprite LoadarrowRight() => Resources.Load<Sprite>(arrowRight);

            public const string arrowUp = "Gameicons/PNG/White/2x/arrowUp";
            public static Sprite LoadarrowUp() => Resources.Load<Sprite>(arrowUp);

            public const string audioOff = "Gameicons/PNG/White/2x/audioOff";
            public static Sprite LoadaudioOff() => Resources.Load<Sprite>(audioOff);

            public const string audioOn = "Gameicons/PNG/White/2x/audioOn";
            public static Sprite LoadaudioOn() => Resources.Load<Sprite>(audioOn);

            public const string barsHorizontal = "Gameicons/PNG/White/2x/barsHorizontal";
            public static Sprite LoadbarsHorizontal() => Resources.Load<Sprite>(barsHorizontal);

            public const string barsVertical = "Gameicons/PNG/White/2x/barsVertical";
            public static Sprite LoadbarsVertical() => Resources.Load<Sprite>(barsVertical);

            public const string button1 = "Gameicons/PNG/White/2x/button1";
            public static Sprite Loadbutton1() => Resources.Load<Sprite>(button1);

            public const string button2 = "Gameicons/PNG/White/2x/button2";
            public static Sprite Loadbutton2() => Resources.Load<Sprite>(button2);

            public const string button3 = "Gameicons/PNG/White/2x/button3";
            public static Sprite Loadbutton3() => Resources.Load<Sprite>(button3);

            public const string buttonA = "Gameicons/PNG/White/2x/buttonA";
            public static Sprite LoadbuttonA() => Resources.Load<Sprite>(buttonA);

            public const string buttonB = "Gameicons/PNG/White/2x/buttonB";
            public static Sprite LoadbuttonB() => Resources.Load<Sprite>(buttonB);

            public const string buttonL = "Gameicons/PNG/White/2x/buttonL";
            public static Sprite LoadbuttonL() => Resources.Load<Sprite>(buttonL);

            public const string buttonL1 = "Gameicons/PNG/White/2x/buttonL1";
            public static Sprite LoadbuttonL1() => Resources.Load<Sprite>(buttonL1);

            public const string buttonL2 = "Gameicons/PNG/White/2x/buttonL2";
            public static Sprite LoadbuttonL2() => Resources.Load<Sprite>(buttonL2);

            public const string buttonR = "Gameicons/PNG/White/2x/buttonR";
            public static Sprite LoadbuttonR() => Resources.Load<Sprite>(buttonR);

            public const string buttonR1 = "Gameicons/PNG/White/2x/buttonR1";
            public static Sprite LoadbuttonR1() => Resources.Load<Sprite>(buttonR1);

            public const string buttonR2 = "Gameicons/PNG/White/2x/buttonR2";
            public static Sprite LoadbuttonR2() => Resources.Load<Sprite>(buttonR2);

            public const string buttonSelect = "Gameicons/PNG/White/2x/buttonSelect";
            public static Sprite LoadbuttonSelect() => Resources.Load<Sprite>(buttonSelect);

            public const string buttonStart = "Gameicons/PNG/White/2x/buttonStart";
            public static Sprite LoadbuttonStart() => Resources.Load<Sprite>(buttonStart);

            public const string buttonX = "Gameicons/PNG/White/2x/buttonX";
            public static Sprite LoadbuttonX() => Resources.Load<Sprite>(buttonX);

            public const string buttonY = "Gameicons/PNG/White/2x/buttonY";
            public static Sprite LoadbuttonY() => Resources.Load<Sprite>(buttonY);

            public const string checkmark = "Gameicons/PNG/White/2x/checkmark";
            public static Sprite Loadcheckmark() => Resources.Load<Sprite>(checkmark);

            public const string contrast = "Gameicons/PNG/White/2x/contrast";
            public static Sprite Loadcontrast() => Resources.Load<Sprite>(contrast);

            public const string cross = "Gameicons/PNG/White/2x/cross";
            public static Sprite Loadcross() => Resources.Load<Sprite>(cross);

            public const string down = "Gameicons/PNG/White/2x/down";
            public static Sprite Loaddown() => Resources.Load<Sprite>(down);

            public const string downLeft = "Gameicons/PNG/White/2x/downLeft";
            public static Sprite LoaddownLeft() => Resources.Load<Sprite>(downLeft);

            public const string downRight = "Gameicons/PNG/White/2x/downRight";
            public static Sprite LoaddownRight() => Resources.Load<Sprite>(downRight);

            public const string exclamation = "Gameicons/PNG/White/2x/exclamation";
            public static Sprite Loadexclamation() => Resources.Load<Sprite>(exclamation);

            public const string exit = "Gameicons/PNG/White/2x/exit";
            public static Sprite Loadexit() => Resources.Load<Sprite>(exit);

            public const string exitLeft = "Gameicons/PNG/White/2x/exitLeft";
            public static Sprite LoadexitLeft() => Resources.Load<Sprite>(exitLeft);

            public const string exitRight = "Gameicons/PNG/White/2x/exitRight";
            public static Sprite LoadexitRight() => Resources.Load<Sprite>(exitRight);

            public const string export = "Gameicons/PNG/White/2x/export";
            public static Sprite Loadexport() => Resources.Load<Sprite>(export);

            public const string fastForward = "Gameicons/PNG/White/2x/fastForward";
            public static Sprite LoadfastForward() => Resources.Load<Sprite>(fastForward);

            public const string gamepad = "Gameicons/PNG/White/2x/gamepad";
            public static Sprite Loadgamepad() => Resources.Load<Sprite>(gamepad);

            public const string gamepad1 = "Gameicons/PNG/White/2x/gamepad1";
            public static Sprite Loadgamepad1() => Resources.Load<Sprite>(gamepad1);

            public const string gamepad2 = "Gameicons/PNG/White/2x/gamepad2";
            public static Sprite Loadgamepad2() => Resources.Load<Sprite>(gamepad2);

            public const string gamepad3 = "Gameicons/PNG/White/2x/gamepad3";
            public static Sprite Loadgamepad3() => Resources.Load<Sprite>(gamepad3);

            public const string gamepad4 = "Gameicons/PNG/White/2x/gamepad4";
            public static Sprite Loadgamepad4() => Resources.Load<Sprite>(gamepad4);

            public const string gear = "Gameicons/PNG/White/2x/gear";
            public static Sprite Loadgear() => Resources.Load<Sprite>(gear);

            public const string home = "Gameicons/PNG/White/2x/home";
            public static Sprite Loadhome() => Resources.Load<Sprite>(home);

            public const string import = "Gameicons/PNG/White/2x/import";
            public static Sprite Loadimport() => Resources.Load<Sprite>(import);

            public const string information = "Gameicons/PNG/White/2x/information";
            public static Sprite Loadinformation() => Resources.Load<Sprite>(information);

            public const string joystick = "Gameicons/PNG/White/2x/joystick";
            public static Sprite Loadjoystick() => Resources.Load<Sprite>(joystick);

            public const string joystickLeft = "Gameicons/PNG/White/2x/joystickLeft";
            public static Sprite LoadjoystickLeft() => Resources.Load<Sprite>(joystickLeft);

            public const string joystickRight = "Gameicons/PNG/White/2x/joystickRight";
            public static Sprite LoadjoystickRight() => Resources.Load<Sprite>(joystickRight);

            public const string joystickUp = "Gameicons/PNG/White/2x/joystickUp";
            public static Sprite LoadjoystickUp() => Resources.Load<Sprite>(joystickUp);

            public const string larger = "Gameicons/PNG/White/2x/larger";
            public static Sprite Loadlarger() => Resources.Load<Sprite>(larger);

            public const string leaderboardsComplex = "Gameicons/PNG/White/2x/leaderboardsComplex";
            public static Sprite LoadleaderboardsComplex() => Resources.Load<Sprite>(leaderboardsComplex);

            public const string leaderboardsSimple = "Gameicons/PNG/White/2x/leaderboardsSimple";
            public static Sprite LoadleaderboardsSimple() => Resources.Load<Sprite>(leaderboardsSimple);

            public const string left = "Gameicons/PNG/White/2x/left";
            public static Sprite Loadleft() => Resources.Load<Sprite>(left);

            public const string locked = "Gameicons/PNG/White/2x/locked";
            public static Sprite Loadlocked() => Resources.Load<Sprite>(locked);

            public const string massiveMultiplayer = "Gameicons/PNG/White/2x/massiveMultiplayer";
            public static Sprite LoadmassiveMultiplayer() => Resources.Load<Sprite>(massiveMultiplayer);

            public const string medal1 = "Gameicons/PNG/White/2x/medal1";
            public static Sprite Loadmedal1() => Resources.Load<Sprite>(medal1);

            public const string medal2 = "Gameicons/PNG/White/2x/medal2";
            public static Sprite Loadmedal2() => Resources.Load<Sprite>(medal2);

            public const string menuGrid = "Gameicons/PNG/White/2x/menuGrid";
            public static Sprite LoadmenuGrid() => Resources.Load<Sprite>(menuGrid);

            public const string menuList = "Gameicons/PNG/White/2x/menuList";
            public static Sprite LoadmenuList() => Resources.Load<Sprite>(menuList);

            public const string minus = "Gameicons/PNG/White/2x/minus";
            public static Sprite Loadminus() => Resources.Load<Sprite>(minus);

            public const string mouse = "Gameicons/PNG/White/2x/mouse";
            public static Sprite Loadmouse() => Resources.Load<Sprite>(mouse);

            public const string movie = "Gameicons/PNG/White/2x/movie";
            public static Sprite Loadmovie() => Resources.Load<Sprite>(movie);

            public const string multiplayer = "Gameicons/PNG/White/2x/multiplayer";
            public static Sprite Loadmultiplayer() => Resources.Load<Sprite>(multiplayer);

            public const string musicOff = "Gameicons/PNG/White/2x/musicOff";
            public static Sprite LoadmusicOff() => Resources.Load<Sprite>(musicOff);

            public const string musicOn = "Gameicons/PNG/White/2x/musicOn";
            public static Sprite LoadmusicOn() => Resources.Load<Sprite>(musicOn);

            public const string next = "Gameicons/PNG/White/2x/next";
            public static Sprite Loadnext() => Resources.Load<Sprite>(next);

            public const string open = "Gameicons/PNG/White/2x/open";
            public static Sprite Loadopen() => Resources.Load<Sprite>(open);

            public const string pause = "Gameicons/PNG/White/2x/pause";
            public static Sprite Loadpause() => Resources.Load<Sprite>(pause);

            public const string phone = "Gameicons/PNG/White/2x/phone";
            public static Sprite Loadphone() => Resources.Load<Sprite>(phone);

            public const string plus = "Gameicons/PNG/White/2x/plus";
            public static Sprite Loadplus() => Resources.Load<Sprite>(plus);

            public const string power = "Gameicons/PNG/White/2x/power";
            public static Sprite Loadpower() => Resources.Load<Sprite>(power);

            public const string previous = "Gameicons/PNG/White/2x/previous";
            public static Sprite Loadprevious() => Resources.Load<Sprite>(previous);

            public const string question = "Gameicons/PNG/White/2x/question";
            public static Sprite Loadquestion() => Resources.Load<Sprite>(question);

            public const string returnArrow = "Gameicons/PNG/White/2x/returnArrow";
            public static Sprite LoadreturnArrow() => Resources.Load<Sprite>(returnArrow);

            public const string rewind = "Gameicons/PNG/White/2x/rewind";
            public static Sprite Loadrewind() => Resources.Load<Sprite>(rewind);

            public const string right = "Gameicons/PNG/White/2x/right";
            public static Sprite Loadright() => Resources.Load<Sprite>(right);

            public const string save = "Gameicons/PNG/White/2x/save";
            public static Sprite Loadsave() => Resources.Load<Sprite>(save);

            public const string scrollHorizontal = "Gameicons/PNG/White/2x/scrollHorizontal";
            public static Sprite LoadscrollHorizontal() => Resources.Load<Sprite>(scrollHorizontal);

            public const string scrollVertical = "Gameicons/PNG/White/2x/scrollVertical";
            public static Sprite LoadscrollVertical() => Resources.Load<Sprite>(scrollVertical);

            public const string share1 = "Gameicons/PNG/White/2x/share1";
            public static Sprite Loadshare1() => Resources.Load<Sprite>(share1);

            public const string share2 = "Gameicons/PNG/White/2x/share2";
            public static Sprite Loadshare2() => Resources.Load<Sprite>(share2);

            public const string shoppingBasket = "Gameicons/PNG/White/2x/shoppingBasket";
            public static Sprite LoadshoppingBasket() => Resources.Load<Sprite>(shoppingBasket);

            public const string shoppingCart = "Gameicons/PNG/White/2x/shoppingCart";
            public static Sprite LoadshoppingCart() => Resources.Load<Sprite>(shoppingCart);

            public const string siganl1 = "Gameicons/PNG/White/2x/siganl1";
            public static Sprite Loadsiganl1() => Resources.Load<Sprite>(siganl1);

            public const string signal2 = "Gameicons/PNG/White/2x/signal2";
            public static Sprite Loadsignal2() => Resources.Load<Sprite>(signal2);

            public const string signal3 = "Gameicons/PNG/White/2x/signal3";
            public static Sprite Loadsignal3() => Resources.Load<Sprite>(signal3);

            public const string singleplayer = "Gameicons/PNG/White/2x/singleplayer";
            public static Sprite Loadsingleplayer() => Resources.Load<Sprite>(singleplayer);

            public const string smaller = "Gameicons/PNG/White/2x/smaller";
            public static Sprite Loadsmaller() => Resources.Load<Sprite>(smaller);

            public const string star = "Gameicons/PNG/White/2x/star";
            public static Sprite Loadstar() => Resources.Load<Sprite>(star);

            public const string stop = "Gameicons/PNG/White/2x/stop";
            public static Sprite Loadstop() => Resources.Load<Sprite>(stop);

            public const string tablet = "Gameicons/PNG/White/2x/tablet";
            public static Sprite Loadtablet() => Resources.Load<Sprite>(tablet);

            public const string target = "Gameicons/PNG/White/2x/target";
            public static Sprite Loadtarget() => Resources.Load<Sprite>(target);

            public const string trashcan = "Gameicons/PNG/White/2x/trashcan";
            public static Sprite Loadtrashcan() => Resources.Load<Sprite>(trashcan);

            public const string trashcanOpen = "Gameicons/PNG/White/2x/trashcanOpen";
            public static Sprite LoadtrashcanOpen() => Resources.Load<Sprite>(trashcanOpen);

            public const string trophy = "Gameicons/PNG/White/2x/trophy";
            public static Sprite Loadtrophy() => Resources.Load<Sprite>(trophy);

            public const string unlocked = "Gameicons/PNG/White/2x/unlocked";
            public static Sprite Loadunlocked() => Resources.Load<Sprite>(unlocked);

            public const string up = "Gameicons/PNG/White/2x/up";
            public static Sprite Loadup() => Resources.Load<Sprite>(up);

            public const string upLeft = "Gameicons/PNG/White/2x/upLeft";
            public static Sprite LoadupLeft() => Resources.Load<Sprite>(upLeft);

            public const string upRight = "Gameicons/PNG/White/2x/upRight";
            public static Sprite LoadupRight() => Resources.Load<Sprite>(upRight);

            public const string video = "Gameicons/PNG/White/2x/video";
            public static Sprite Loadvideo() => Resources.Load<Sprite>(video);

            public const string warning = "Gameicons/PNG/White/2x/warning";
            public static Sprite Loadwarning() => Resources.Load<Sprite>(warning);

            public const string wrench = "Gameicons/PNG/White/2x/wrench";
            public static Sprite Loadwrench() => Resources.Load<Sprite>(wrench);

            public const string zoom = "Gameicons/PNG/White/2x/zoom";
            public static Sprite Loadzoom() => Resources.Load<Sprite>(zoom);

            public const string zoomDefault = "Gameicons/PNG/White/2x/zoomDefault";
            public static Sprite LoadzoomDefault() => Resources.Load<Sprite>(zoomDefault);

            public const string zoomIn = "Gameicons/PNG/White/2x/zoomIn";
            public static Sprite LoadzoomIn() => Resources.Load<Sprite>(zoomIn);

            public const string zoomOut = "Gameicons/PNG/White/2x/zoomOut";
            public static Sprite LoadzoomOut() => Resources.Load<Sprite>(zoomOut);

        }

        public static partial class TextAssets
        {

            public const string license = "Gameicons/license";
            public static TextAsset Loadlicense() => Resources.Load<TextAsset>(license);

            public const string sheet_black1x = "Gameicons/Spritesheet/sheet_black1x";
            public static TextAsset Loadsheet_black1x() => Resources.Load<TextAsset>(sheet_black1x);

            public const string sheet_black2x = "Gameicons/Spritesheet/sheet_black2x";
            public static TextAsset Loadsheet_black2x() => Resources.Load<TextAsset>(sheet_black2x);

            public const string sheet_white1x = "Gameicons/Spritesheet/sheet_white1x";
            public static TextAsset Loadsheet_white1x() => Resources.Load<TextAsset>(sheet_white1x);

            public const string sheet_white2x = "Gameicons/Spritesheet/sheet_white2x";
            public static TextAsset Loadsheet_white2x() => Resources.Load<TextAsset>(sheet_white2x);

            public const string BillingMode = "BillingMode";
            public static TextAsset LoadBillingMode() => Resources.Load<TextAsset>(BillingMode);

        }

        public static partial class Layers
        {

            public const string Default = "Default";
            public static int GetDefaultIndex() => LayerMask.NameToLayer(Default);
            public static int GetDefaultMask() => LayerMask.GetMask(Default);
            public const string TransparentFX = "TransparentFX";
            public static int GetTransparentFXIndex() => LayerMask.NameToLayer(TransparentFX);
            public static int GetTransparentFXMask() => LayerMask.GetMask(TransparentFX);
            public const string IgnoreRaycast = "Ignore Raycast";
            public static int GetIgnoreRaycastIndex() => LayerMask.NameToLayer(IgnoreRaycast);
            public static int GetIgnoreRaycastMask() => LayerMask.GetMask(IgnoreRaycast);
            public const string Water = "Water";
            public static int GetWaterIndex() => LayerMask.NameToLayer(Water);
            public static int GetWaterMask() => LayerMask.GetMask(Water);
            public const string UI = "UI";
            public static int GetUIIndex() => LayerMask.NameToLayer(UI);
            public static int GetUIMask() => LayerMask.GetMask(UI);
        }

#if UNITY_EDITOR
        public static partial class LoadSceneButtons
        {

            [UnityEditor.MenuItem("Load Scene / GameScene")]
            public static void LoadGameScene()
            {
                UnityEditor.SceneManagement.EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo();
                UnityEditor.SceneManagement.EditorSceneManager.OpenScene(@"Assets\TradeCity.Unity\Scenes\GameScene.unity");
            }
            [UnityEditor.MenuItem("Load Scene / MainMenu")]
            public static void LoadMainMenu()
            {
                UnityEditor.SceneManagement.EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo();
                UnityEditor.SceneManagement.EditorSceneManager.OpenScene(@"Assets\TradeCity.Unity\Scenes\MainMenu.unity");
            }

        }
#endif

}